name: Lint
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: wow-lint
        uses: davidcraig/action-wow-lint@v1.0.1
        with:
            path-to-files: 'main.lua Libs/ClassSpells-1.0/*.lua'
